name: clean_arch_movie
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

  #State Manager
  mobx: ^2.2.0
  flutter_mobx: ^2.0.6+5

  #Dependency injection
  injectable: ^2.1.2
  get_it: ^7.6.0

  #local storage
  sqflite: ^2.3.0

  #Firebase
  firebase_core: ^2.15.0
  firebase_crashlytics: ^3.3.4
  firebase_remote_config: ^4.2.4

  #router
  go_router: ^10.0.0

  #utils
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  mobx_codegen: ^2.3.0
  injectable_generator: ^2.1.6
  go_router_builder: ^2.2.4

flutter:

  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg